version: ~> 1.0

env:
  global:
    # Doctr deploy key for pcdshub/hxr-attenuator
    - secure: "U3jbzc8qZZf8DSNM6ElQSh6ScbpTg752I/ng9iXVmfcaMX5C99EmdKfkZgzDCvjCy6zngUQiJNOEjgU8Tgff8W2cKvb/YH+N56wmlHD1B2UKnAzsRWsIdh8Mwd0wlibh8Pza/Dxp+TpSfM281UFUYo9BcszJWevb/2Gw0iNQEBRDCKxvzGFG/8dq7i0RnqRP8All+rtZYr9EAHkiXXX0gBJBiMQJLAk6GE5wvrGMqkcHvwkUzl0M3HHLgfKCKdG/wuU6Wnzte5e4gd7Lbt5IziyAaDF1TFYen/qGVvVChdt13OttPM8JSHNz0nnGqo7ngux/3JRucZM5J0w5oQhZIf9NE50FalVej3tOFy6DvvmNpTgGW7OHhutZfC5qAHAfeC3nzyLfegJW38XQm0FW6SUEoDRdt5M6eUW3Q7znMX6ejO1obw1nzv1aV8bXSdilwd7HfDtOWnI2oGAZdMVoL39di6jH2oCM2cREePCM9XELWhpA+cY5kiw9wyZ9yWbUhiKCnqsSuWnWNXwElq+UAptUqSud4bKCRSb4LlTaL9DkgpXR18ep0L+1k5OZUGzLfuYx0ISJS+GKfQGMCwIpiKFMYisYNG2xVTsIldEgq8Lc6ZALOn3YrMGNagTPujiI8f9SahWC+9L92x9WoPVsK1l+98scZ6Tedm2CK4hPBq8="

    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"
    # Dependency files used to build the documentation (space separated)
    - DOCS_REQUIREMENTS="dev-requirements.txt requirements.txt"
    # Options to be passed to flake8 for package linting. Usually this is just
    # the package name but you can enable other flake8 options via this config
    - PYTHON_LINT_OPTIONS="hxr_attenuator"

    # The name of the conda package
    - CONDA_PACKAGE="hxr_attenuator"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"
    # Extra dependencies needed to run the tests which are not included
    # in the recipe or CONDA_REQUIREMENTS. E.g. PyQt
    - CONDA_EXTRAS=""
    # Requirements file with contents for tests dependencies
    - CONDA_REQUIREMENTS="dev-requirements.txt"

    # Extra dependencies needed to run the test with Pip (similar to
    # CONDA_EXTRAS) but for pip
    - PIP_EXTRAS=""

# jobs:
#   allow_failures:
#     # This makes the PIP based Python 3.6 optional for passing.
#     # Remove this block if passing tests with PIP is mandatory for your
#     # package
#     - name: "Python 3.6 - PIP"

import:
  # This import enables a set of standard python jobs including:
  # - Build
  #   - Anaconda Package Build
  # - Tests
  #   - Linter
  #   - Documentation
  #   - Python 3.6 - PIP based
  #   - Python 3.6, 3.7 & 3.8 - Conda base
  # - Deploy
  #   - Documentation using doctr
  #   - Conda Package - uploaded to pcds-dev and pcds-tag
  #   - PyPI
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda.yml
